### ISSUE TITLE
Continue button on post-submit form does nothing

### ISSUE THREAD

**Issue by rerb** [AASHE/aashe-bulletin#12]
<img width="1205" alt="screen shot 2017-03-11 at 1 29 11 pm" src="https://cloud.githubusercontent.com/assets/609008/23825802/bfb6b5ea-065e-11e7-9254-29fbf92781ac.png">

**Comment by juliandsmith** [comment]
This appears to have been resolved. The continue button links to the [all-items page](https://bulletin.aashe.org/all-items/).
